### ISSUE TITLE
发现Readme文档有处小错误

### ISSUE THREAD

**Issue by shazi4399** [FudanMPL/Garnet#33]
在[数据准备](https://github.com/FudanMPL/Garnet/tree/main#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87-1)这一部分。
```
python ./Scripts/data_prepare_for_decision_tree.py IRIS

以下为控制台输出
file: ./Data/IRIS_train.csv
items: 135
attributes: 4
file: ./Data/IRIS_test.csv
items: 15
attributes: 4
```
`python ./Scripts/data_prepare_for_decision_tree.py IRIS`
应该修改为
`python ./Scripts/data_prepare_for_xgboost.py IRIS`

**Comment by GuopengLin** [comment]
感谢指出错误！
