### ISSUE TITLE
FSS优化问题

### ISSUE THREAD

**Issue by addingIce** [FudanMPL/Garnet#48]
请问有关 FSS 的优化，是否有相关 paper 可参考？
另外在 https://github.com/FudanMPL/Garnet/blob/main/docs/fss.md 给出的旧版测试结果中，虽然使用 FSS 后通信总量下降，但总耗时是原始协议的10倍；根据最新更新信息，目前使用 FSS 性能会比原来快10倍，是否有相应的测试结果？

**Comment by SkyTu** [comment]
感谢您提出的问题，关于FSS性能比原本快10倍是相对于之前没有关闭offline的情况下快10倍，这个结论是错误的，我重新测试后应当是2-3倍。

之所以会发生这个错误是因为在9月20日我测试在64比特的环上面测试结果为：
```
No online generating
FSS
Time = 0.179097 seconds 
Data sent = 0.0056 MB in ~600 rounds (party 0)
Global data sent = 0.0184 MB (all parties)

RSS
Time = 0.153999 seconds 
Data sent = 0.0496 MB in ~900 rounds (party 0)
Global data sent = 0.1488 MB (all parties)
```
因此我误认为fss和rss在速度上基本一致了，那么和之前结果相比，确实总耗时缩短了十倍。

为了更进一步解决这个问题，我今天重新测试了一下这份代码，发现当时的运行结果是存在问题的，实际效果应该只提速了2-3倍左右，我会在新的readme中进行对应的修改。

这个速度的提升主要来自于通信部分的代码优化以及关闭了fss中的dcf key generation这部分的代码（目前并没有提供一个对应的参数进行调整，需要手动生成dcf key后将生成部分的代码注释掉，我将在后续的部分进行对应的修改，并添加对应的参数接口），以下是关闭了offline的dcf key generation的测试结果

之前的通信轮次在关闭offline的情况下是每次比较7轮，但是没有关闭fss的offline阶段生成的代码，这次发现这个问题后重新测试，在测试的时候关闭了offline阶段的代码，测试结果如下图所示：
```
Trying to run 128-bit computation
REWINDING - ONLY FOR BENCHMARKING
The following benchmarks are excluding preprocessing (offline phase).
Time = 23.5479 seconds 
Data sent = 1.12 MB in ~60000 rounds (party 0)
Global data sent = 3.68 MB (all parties)
```
总体时间上是原本的1/3。
