### ISSUE TITLE
为什么Garnet的FSS是以RSS为基础

### ISSUE THREAD

**Issue by shazi4399** [FudanMPL/Garnet#52]
有个疑问，为什么Garnet的函数秘密共享（FSS）是以Replicate secret share为基础。而不是以两方的秘密共享为基础。

**Comment by SkyTu** [comment]
您好，是因为之前有个项目要用到三方的转换，所以就基于RSS实现了函数秘密共享。

**Comment by shazi4399** [comment]
谢谢解答~
