### ISSUE TITLE
请问 Garnet 是在MP-SPDZ哪个版本基础上进行修改的

### ISSUE THREAD

**Issue by shazi4399** [FudanMPL/Garnet#63]
你好，

请问 Garnet 是在MP-SPDZ哪个基础上改进的，可以给出MP-SPDZ明确的版本号或者具体的commit哈希串吗。

**Comment by GuopengLin** [comment]
应该是2023年2月7号的commit上进行的改进，commit id 为25c49abcf1621d8122309beb4693517787262bcb

**Comment by shazi4399** [comment]
感谢~
