### ISSUE TITLE
SecureML issue

### ISSUE THREAD

**Issue by yimingqincs** [FudanMPL/Garnet#81]
I follow the "secureml.md" document. 

When I input the "make -j 8 sml-party.x" statement, it appear any errors.

```
./Tools_PSI/SimpleIndex.h:12:10: fatal error: cryptoTools/Common/Defines.h: No such file or directory
   12 | #include "cryptoTools/Common/Defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Machines/sml-party.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./Protocols/Semi.h:12,
                 from ./Protocols/SemiShare.h:10,
                 from ./Protocols/Semi2kShare128.h:8,
                 from Processor/Processor.h:10,
                 from Processor/Instruction.cpp:8:
./Tools_PSI/SimpleIndex.h:12:10: fatal error: cryptoTools/Common/Defines.h: No such file or directory
   12 | #include "cryptoTools/Common/Defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/Instruction.o] Error 1
In file included from ./Protocols/Semi.h:12,
                 from ./Protocols/SemiShare.h:10,
                 from ./Protocols/Semi2kShare128.h:8,
                 from ./Processor/Processor.h:10,
                 from ./Protocols/ReplicatedInput.h:10,
                 from ./Protocols/Rep3Share128.h:12,
                 from ./Processor/Machine.h:25,
                 from Processor/HonestMajorityMachine.cpp:13:
./Tools_PSI/SimpleIndex.h:12:10: fatal error: cryptoTools/Common/Defines.h: No such file or directory
   12 | #include "cryptoTools/Common/Defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/HonestMajorityMachine.o] Error 1
```

It may lack the "cryptoTools/Common/Defines.h" file.  Could you please debug and submit the correct version which can be compiled successfully.

**Comment by yimingqincs** [comment]
This program lacks the cryptoTools/Common/Defines.h. Is this error caused by missing "cryptotools“. But I don't find it in Garnet Folder.
I find the cryptoTools in https://github.com/ladnir/cryptoTools. If I add this in my program, will it be compiled successfully.

**Comment by GuopengLin** [comment]
Hello, which version did you use? Please execute "git pull" to update to the latest version. 

Besides, did you execute "make -j8 tldr" before executing "make -j 8 sml-party.x"?
Please make sure the command "make -j8 tldr" is completed. If so, it will produce a "mascot-party.x" in the directory Garnet/.

**Comment by yimingqincs** [comment]
Yes, I  execute   "make -j8 tldr" before executing "make -j 8 sml-party.x"

**Comment by GuopengLin** [comment]
When did you download the source code?
I just downloaded the code by git clone, and executed "make -j8 tldr" and "make -j 8 sml-party.x". It seems everything is ok.
Please check whether "make -j8 tldr" is executed successfully. If it is executed successfully, these will be a "mascot-party.x" file in the directory Garnet/.

**Comment by yimingqincs** [comment]
When I excute "Scripts/setup-ssl.sh 2" , it will appear this 

Scripts/setup-ssl.sh: /home/yqin0020/anaconda3/envs/Grant/bin/c_rehash: /croot/openssl_1694464909176/_build_env/bin/perl: bad interpreter: No such file or directory

**Comment by yimingqincs** [comment]
``
(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ ./compile.py -R 64 tutorial
Default bit length: 63
Default security parameter: 40
Compiling file /home/yqin0020/Desktop/New Folder/Garnet/Programs/Source/tutorial.mpc
Processing basic block Sun May  5 21:02:59 2024
WARNING: Order of memory instructions not preserved, errors possible
profiling time: 0.013077020645141602
Writing to /home/yqin0020/Desktop/New Folder/Garnet/Programs/Schedules/tutorial.sch
Writing to /home/yqin0020/Desktop/New Folder/Garnet/Programs/Bytecode/tutorial-0.bc
Program requires at most:
      790080 online communication bits
     5398848 offline communication bits
         674 online round
       14810 offline round
compiling time: 2.398174524307251
(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ make -j 8 sml-party.x
git submodule update --init deps/SimpleOT || git clone https://github.com/mkskeller/SimpleOT deps/SimpleOT
git submodule update --init deps/SimplestOT_C || git clone https://github.com/mkskeller/SimplestOT_C deps/SimplestOT_C
git submodule update --init --recursive deps/libOTe || git clone --recurse-submodules https://github.com/mkskeller/softspoken-implementation deps/libOTe
g++ -o Machines/sml-party.o Machines/sml-party.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/BaseMachine.o Processor/BaseMachine.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/DataPositions.o Processor/DataPositions.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/ExternalClients.o Processor/ExternalClients.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/FixInput.o Processor/FixInput.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
Submodule 'deps/SimplestOT_C' (https://github.com/mkskeller/SimplestOT_C) registered for path 'deps/SimplestOT_C'
Submodule 'SimpleOT' (https://github.com/mkskeller/SimpleOT) registered for path 'deps/SimpleOT'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimplestOT_C'...
Submodule 'deps/libOTe' (https://github.com/mkskeller/softspoken-implementation) registered for path 'deps/libOTe'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimpleOT'...
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe'...
In file included from Processor/FixInput.h:11,
                 from Processor/FixInput.cpp:6:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/FixInput.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./Math/Setup.h:9,
                 from ./Networking/ssl_sockets.h:12,
                 from ./Processor/ExternalClients.h:5,
                 from Processor/ExternalClients.cpp:1:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/ExternalClients.o] Error 1
In file included from ./Protocols/Replicated.h:17,
                 from ./Protocols/Beaver.h:13,
                 from ./Protocols/SemiShare.h:9,
                 from ./Protocols/SmlShare.h:9,
                 from Machines/sml-party.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Machines/sml-party.o] Error 1
In file included from ./OT/BaseOT.h:12,
                 from ./OT/OTTripleSetup.h:5,
                 from Processor/BaseMachine.h:11,
                 from Processor/BaseMachine.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/BaseMachine.o] Error 1
Submodule path 'deps/SimplestOT_C': checked out '033e24280ae32d599c5b037b44edd7c7e8228b35'
cd deps/SimplestOT_C/ref10; PATH=/home/yqin0020/Desktop/New Folder/Garnet/local/bin:/home/yqin0020/anaconda3/envs/Grant/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin cmake .
/bin/sh: 1: Folder/Garnet/local/bin:/home/yqin0020/anaconda3/envs/Grant/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin: not found
make: *** [Makefile:305: deps/SimplestOT_C/ref10/Makefile] Error 127
Submodule path 'deps/SimpleOT': checked out '84d73522619f90ba2aabce8d660baef1442aa26d'
Submodule path 'deps/libOTe': checked out 'cd89232ffac74286a4963d93480db44cbf604c41'
Submodule 'cryptoTools' (https://github.com/mkskeller/softspoken-implementation-cryptotools) registered for path 'deps/libOTe/cryptoTools'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools'...
Submodule path 'deps/libOTe/cryptoTools': checked out '581eaeb9cbda17f814bde9b6a2ba092957991e3b'
Submodule 'thirdparty/simde' (https://github.com/simd-everywhere/simde) registered for path 'deps/libOTe/cryptoTools/thirdparty/simde'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools/thirdparty/simde'...
Submodule path 'deps/libOTe/cryptoTools/thirdparty/simde': checked out '0ba20859e9f557cee161d2cab2728b56dca7ec38'
Submodule 'munit' (https://github.com/nemequ/munit.git) registered for path 'deps/libOTe/cryptoTools/thirdparty/simde/test/munit'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools/thirdparty/simde/test/munit'...
Submodule path 'deps/libOTe/cryptoTools/thirdparty/simde/test/munit': checked out 'da8f73412998e4f1adf1100dc187533a51af77fd'
(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ Scripts/sml.sh tutorial
Scripts/sml.sh: line 6: /home/yqin0020/Desktop/New: No such file or directory
Scripts/sml.sh: line 8: run_player: command not found

``

**Comment by yimingqincs** [comment]
`(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ ./compile.py -R 64 tutorial
Default bit length: 63
Default security parameter: 40
Compiling file /home/yqin0020/Desktop/New Folder/Garnet/Programs/Source/tutorial.mpc
Processing basic block Sun May  5 21:02:59 2024
WARNING: Order of memory instructions not preserved, errors possible
profiling time: 0.013077020645141602
Writing to /home/yqin0020/Desktop/New Folder/Garnet/Programs/Schedules/tutorial.sch
Writing to /home/yqin0020/Desktop/New Folder/Garnet/Programs/Bytecode/tutorial-0.bc
Program requires at most:
      790080 online communication bits
     5398848 offline communication bits
         674 online round
       14810 offline round
compiling time: 2.398174524307251
(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ make -j 8 sml-party.x
git submodule update --init deps/SimpleOT || git clone https://github.com/mkskeller/SimpleOT deps/SimpleOT
git submodule update --init deps/SimplestOT_C || git clone https://github.com/mkskeller/SimplestOT_C deps/SimplestOT_C
git submodule update --init --recursive deps/libOTe || git clone --recurse-submodules https://github.com/mkskeller/softspoken-implementation deps/libOTe
g++ -o Machines/sml-party.o Machines/sml-party.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/BaseMachine.o Processor/BaseMachine.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/DataPositions.o Processor/DataPositions.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/ExternalClients.o Processor/ExternalClients.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/FixInput.o Processor/FixInput.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
Submodule 'deps/SimplestOT_C' (https://github.com/mkskeller/SimplestOT_C) registered for path 'deps/SimplestOT_C'
Submodule 'SimpleOT' (https://github.com/mkskeller/SimpleOT) registered for path 'deps/SimpleOT'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimplestOT_C'...
Submodule 'deps/libOTe' (https://github.com/mkskeller/softspoken-implementation) registered for path 'deps/libOTe'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimpleOT'...
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe'...
In file included from Processor/FixInput.h:11,
                 from Processor/FixInput.cpp:6:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/FixInput.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./Math/Setup.h:9,
                 from ./Networking/ssl_sockets.h:12,
                 from ./Processor/ExternalClients.h:5,
                 from Processor/ExternalClients.cpp:1:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/ExternalClients.o] Error 1
In file included from ./Protocols/Replicated.h:17,
                 from ./Protocols/Beaver.h:13,
                 from ./Protocols/SemiShare.h:9,
                 from ./Protocols/SmlShare.h:9,
                 from Machines/sml-party.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Machines/sml-party.o] Error 1
In file included from ./OT/BaseOT.h:12,
                 from ./OT/OTTripleSetup.h:5,
                 from Processor/BaseMachine.h:11,
                 from Processor/BaseMachine.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/BaseMachine.o] Error 1
Submodule path 'deps/SimplestOT_C': checked out '033e24280ae32d599c5b037b44edd7c7e8228b35'
cd deps/SimplestOT_C/ref10; PATH=/home/yqin0020/Desktop/New Folder/Garnet/local/bin:/home/yqin0020/anaconda3/envs/Grant/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin cmake .
/bin/sh: 1: Folder/Garnet/local/bin:/home/yqin0020/anaconda3/envs/Grant/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin: not found
make: *** [Makefile:305: deps/SimplestOT_C/ref10/Makefile] Error 127
Submodule path 'deps/SimpleOT': checked out '84d73522619f90ba2aabce8d660baef1442aa26d'
Submodule path 'deps/libOTe': checked out 'cd89232ffac74286a4963d93480db44cbf604c41'
Submodule 'cryptoTools' (https://github.com/mkskeller/softspoken-implementation-cryptotools) registered for path 'deps/libOTe/cryptoTools'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools'...
Submodule path 'deps/libOTe/cryptoTools': checked out '581eaeb9cbda17f814bde9b6a2ba092957991e3b'
Submodule 'thirdparty/simde' (https://github.com/simd-everywhere/simde) registered for path 'deps/libOTe/cryptoTools/thirdparty/simde'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools/thirdparty/simde'...
Submodule path 'deps/libOTe/cryptoTools/thirdparty/simde': checked out '0ba20859e9f557cee161d2cab2728b56dca7ec38'
Submodule 'munit' (https://github.com/nemequ/munit.git) registered for path 'deps/libOTe/cryptoTools/thirdparty/simde/test/munit'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/libOTe/cryptoTools/thirdparty/simde/test/munit'...
Submodule path 'deps/libOTe/cryptoTools/thirdparty/simde/test/munit': checked out 'da8f73412998e4f1adf1100dc187533a51af77fd'
(Grant) yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ Scripts/sml.sh tutorial
Scripts/sml.sh: line 6: /home/yqin0020/Desktop/New: No such file or directory
Scripts/sml.sh: line 8: run_player: command not found`

**Comment by GuopengLin** [comment]
```/croot/openssl_1694464909176/_build_env/bin/perl: bad interpreter: No such file or directory```

This error will occur if execute ```"Scripts/setup-ssl.sh 2"```  in a conda environment.
You can first disable the conda environment by execute ```conda deactivate```, then execute "Scripts/setup-ssl.sh 2" again.

**Comment by yimingqincs** [comment]
when I excute `make -j8 tldr`, it appear this error.

`-- Could NOT find Boost: Found unsuitable version "1.74.0", but required is at least "1.75" (found /usr/include, found components: system thread chrono date_time atomic)
CMake Error at cryptoTools/cmake/cryptoToolsDepHelper.cmake:213 (message):
  Failed to find boost 1.75+ at "" or at system install
Call Stack (most recent call first):
  cryptoTools/CMakeLists.txt:90 (include)
`

**Comment by GuopengLin** [comment]
Yes, this error will affect the compile.
Please wait for a moment, I will update the source code, so that you do not need to update the boost version manually.

**Comment by yimingqincs** [comment]
yesterday I update the boost library 1.85. I don't why it can appear this error.

**Comment by GuopengLin** [comment]
Maybe the soft link to boost is not updated. 

I just updated the source code and readme file, please download again. If there are still some problems, please contact me in this issue.

**Comment by yimingqincs** [comment]
`yqin0020@MU00232663L:~/Desktop/New Folder/Garnet$ make -j 8 sml-party.x
git submodule update --init deps/SimpleOT || git clone https://github.com/mkskeller/SimpleOT deps/SimpleOT
git submodule update --init deps/SimplestOT_C || git clone https://github.com/mkskeller/SimplestOT_C deps/SimplestOT_C
g++ -o Machines/sml-party.o Machines/sml-party.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/BaseMachine.o Processor/BaseMachine.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/DataPositions.o Processor/DataPositions.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/ExternalClients.o Processor/ExternalClients.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/FixInput.o Processor/FixInput.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
g++ -o Processor/FloatInput.o Processor/FloatInput.cpp -I./local/include -march=native  -g -Wextra -Wall  -I. -I./deps -pthread    -DUSE_GF2N_LONG '-DPREP_DIR="Player-Data/"' '-DSSL_DIR="Player-Data/"'  -std=c++11  -std=c++17 -fPIC -g -D ENABLE_PSI=true -MMD -MP -c
Submodule 'SimpleOT' (https://github.com/mkskeller/SimpleOT) registered for path 'deps/SimpleOT'
Submodule 'deps/SimplestOT_C' (https://github.com/mkskeller/SimplestOT_C) registered for path 'deps/SimplestOT_C'
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimplestOT_C'...
Cloning into '/home/yqin0020/Desktop/New Folder/Garnet/deps/SimpleOT'...
In file included from Processor/FixInput.h:11,
                 from Processor/FixInput.cpp:6:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/FixInput.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from Processor/FloatInput.h:9,
                 from Processor/FloatInput.cpp:6:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/FloatInput.o] Error 1
In file included from ./Math/Setup.h:9,
                 from ./Networking/ssl_sockets.h:12,
                 from ./Processor/ExternalClients.h:5,
                 from Processor/ExternalClients.cpp:1:
./Math/bigint.h:8:10: fatal error: mpirxx.h: No such file or directory
    8 | #include <mpirxx.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/ExternalClients.o] Error 1
In file included from ./Protocols/Replicated.h:17,
                 from ./Protocols/Beaver.h:13,
                 from ./Protocols/SemiShare.h:9,
                 from ./Protocols/SmlShare.h:9,
                 from Machines/sml-party.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Machines/sml-party.o] Error 1
In file included from ./OT/BaseOT.h:12,
                 from ./OT/OTTripleSetup.h:5,
                 from Processor/BaseMachine.h:11,
                 from Processor/BaseMachine.cpp:6:
./Tools/random.h:10:10: fatal error: mpir.h: No such file or directory
   10 | #include <mpir.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:80: Processor/BaseMachine.o] Error 1
Submodule path 'deps/SimplestOT_C': checked out '033e24280ae32d599c5b037b44edd7c7e8228b35'
cd deps/SimplestOT_C/ref10; PATH=/home/yqin0020/Desktop/New Folder/Garnet/local/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin cmake .
/bin/sh: 1: Folder/Garnet/local/bin:/home/yqin0020/anaconda3/condabin:/home/yqin0020/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda/bin: not found
make: *** [Makefile:305: deps/SimplestOT_C/ref10/Makefile] Error 127
Submodule path 'deps/SimpleOT': checked out ''
`I

it appear this

**Comment by yimingqincs** [comment]
Do you have spare time to have a meeting with me in tencent meeting or Zoom?

**Comment by GuopengLin** [comment]
ok, please leave your wechat

**Comment by yimingqincs** [comment]
qinym981007
